export const LOGIN_USER_REQUEST = 'LOGIN_USER_REQUEST';
export const LOGIN_USER_FAILURE = 'LOGIN_USER_FAILURE';
export const LOGIN_USER_SUCCESS = 'LOGIN_USER_SUCCESS';
export const LOGOUT_USER = 'LOGOUT_USER';

export const GET_PROSPECT_REQUEST = 'GET_PROSPECT_REQUEST';
export const GET_PROSPECT_FAILURE = 'GET_PROSPECT_FAILURE';
export const GET_PROSPECT_SUCCESS = 'GET_PROSPECT_SUCCESS';
